name: Deploy And Wake
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: AzureFunctionsDiscordBot
        package: './output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE  }}
 
    - name: Wake Azure Function 
      run: curl -X GET "https://azurefunctionsdiscordbotwithcalc.azurewebsites.net/api/DiscordBotFunction?code=${{ secrets.AZURE_FUNCTIONAPP_DEFAULT_KEY  }}"
