name: Deploy Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Azure CLI
      uses: azure/CLI@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Azure Functions App
      run: |
        func azure functionapp publish AzureFunctionsDiscordBot
 
    - name: Wake Azure Function 
      run: curl -X GET "https://azurefunctionsdiscordbotwithcalc.azurewebsites.net"
